---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8'
  
dependencies:
  galaxy: requirements.yml
  python: requirements.txt

#additional_build_steps:
#  prepend: |
#    RUN pip3 install --upgrade pip setuptools
#    RUN whoami
#    RUN cat /etc/os-release
#  append:
#    - RUN echo This is a post-install command!
#    - RUN ls -la /etc