## Be sure path is writable
backup_path : '/home/ansible_automation/ansible/pan_aap_labsV1/project/'
## Set to true to backup config
backup_configuration: 'false'
## Insert name of backup file to restore. If blank no restoration will occur
## For restore ensure backup_configuration = true. Config will be backed up prior to restore of file
restore_file: 'backup-2022-10-27-18-57.xml'
restore_configuration: 'true'
